export * from "./arrow-right";
export * from "./download";
export * from "./github";
export * from "./linkedin";
export * from "./moon";
export * from "./paper-plane";
export * from "./sun";
export * from "./whats-app";
export * from "./world";
